In [12]:
import numpy as np
nx, ny = (3, 2)
x = np.linspace(0, 1, nx)
y = np.linspace(0, 2, ny)
xv, yv = np.meshgrid(y,x)

In [13]:
x

array([0. , 0.5, 1. ])

In [14]:
y

array([0., 2.])

In [15]:
xv

array([[0., 2.],
       [0., 2.],
       [0., 2.]])

In [16]:
yv

array([[0. , 0. ],
       [0.5, 0.5],
       [1. , 1. ]])